name: penny
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "lib/images/icon.png"
  image_path_ios: "lib/images/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/images/
